server:
  port: 8189
  servlet:
    context-path: /app
spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL;DATABASE_TO_UPPER=false
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:/db/migration/
